image: alpine:3

minimize_deploy:
  stage: deploy
  script:
    - "curl -X POST --fail -F token=${GITLAB_TRIGGER_PIPELINE_TOKEN} -F ref=master -F variables[IHB_JSON_NAME]=Portable-Desktop-Uninterruptible-Power-Supply https://gitlab.soraharu.com/api/v4/projects/34/trigger/pipeline"
